### ISSUE TITLE
Table of contents tab looks like a header

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#172]
The tab to toggle between "Latest Revisions" and the table of contents looks like a header and so people cannot find it.

This needs to be fixed so that the tabs actually look like tabs. Additionally "Content" should say "Contents"

![Image](https://github.com/user-attachments/assets/954e523a-f6ef-4da0-9510-cd0487d8c3d7)

![Image](https://github.com/user-attachments/assets/477c97f8-a2fe-406f-b02e-0ae1d4cd025a)

**Comment by Kale98** [comment]
This has been deployed on BETA env. (https://sancho.constitution.gov.tools/).
