### ISSUE TITLE
My Actions page tabs look like headers

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#173]
The tabs on the My Actions page look like they cannot be selected. They need to look like tabs or people will not understand how to navigate the website. 

![Image](https://github.com/user-attachments/assets/6872cb6d-bec7-48ee-94d2-f367e8fcb4fe)

**Comment by Kale98** [comment]
This has been on BETA env. (https://sancho.constitution.gov.tools/).
