### ISSUE TITLE
heartbreaking dates

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#215]
At the ICC training session, a number of members of the ICC consortia expressed that date formats are expressed differently in different parts of the world. dd/mm/yyyy vs mm/dd/yyyy, and that in different timezones the date could be incorrect.

### Solutions that they suggested

- mm/yyyy date format
- epoch numbers instead of dates (this was the consensus preferred option

### Other potential solutions
- yyyy/mm/dd format
- display timezone next to dates

QUESTION: 
How easy would it be to display an epoch number? 

SOLUTION:
~~Please change the date format to `yyyy.mm.dd (timezone)`. Where timezone is the timezone the date is recorded in e.g. `2024.07.26 (UTC)
`
Then later on we can move to epoch numbers when we have some time and budget.~~

**Please align with the date format followed by GovTool as [explained](https://github.com/IntersectMBO/cc-portal/issues/215#issuecomment-2255701945) by @bosko-m below.**

**Comment by Kale98** [comment]
This has been deployed to both SanchoNet and MainNet.
