### ISSUE TITLE
Rationale format check

### ISSUE THREAD

**Issue by Kale98** [IntersectMBO/cc-portal#223]
Could you please confirm that the rationale format is OK or you are expecting something else?

For the Rationale of the Governance Action Proposal, we send a JSON object to the IPFS with the following fields:
{
"govActionProposalTxHash":"edef927af962664ed7a02bedfa913c7f1cd271494871c25ee7de66e941d83c79",
   "title":"test reasoning",
   "content":"some text of reasoning"
}
As a result, we get CID for that JSON content.

cc @Ryun1 @Thomas-Upfield @bosko-m

**Comment by Kale98** [comment]
This has been on BETA env. (https://sancho.constitution.gov.tools/).

**Comment by bosko-m** [comment]
@Kale98 Can you please specify whats deployed on BETA env exactly? Is it according to suggestions and json examples from @Ryun1 here - https://github.com/IntersectMBO/cc-portal/issues/223#issuecomment-2260752491?
CC @Thomas-Upfield

**Comment by Kale98** [comment]
Sure @bosko-m. 

Changelog: Removed title as instructed by Ryan. The new format contains the author and reference fields, but they are empty for now, that is, for version 1, which is on Sanchonet, because there is currently no UI for them (according to the approved design). We can consider how to 'upgrade' in future versions. Also, I'm sending you an example of how it looks now with the changes explained above.


[rationale_example_v1.json](https://github.com/user-attachments/files/16816251/rationale_example_v1.json)

cc @Ryun1 @bosko-m

**Comment by Thomas-Upfield** [comment]
@bosko-m @Kale98 I am happy to release if the situation is as described. @Kale98 is this currently deployed to sancho.constitution.gov.tools?

**Comment by Kale98** [comment]
Yes, it is. @Thomas-Upfield 

cc @bosko-m @Ryun1

**Comment by Thomas-Upfield** [comment]
Thank you @Kale98, @Ryun1 please could you check that the updated format is correct?

**Comment by Ryun1** [comment]
@Kale98 @Thomas-Upfield @Kale98 

> [rationale_example_v1.json](https://github.com/user-attachments/files/16816251/rationale_example_v1.json)

Eyeballing it this looks fine,
as per [the schema](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/cip-0100.common.schema.json) `references` is not required, so if you dont have any you can just remove them

>  That is, for version 1, which is on Sanchonet, because there is currently no UI for them (according to the approved design). We can consider how to 'upgrade' in future versions

I would strongly consider adding support for the other CIP-100 fields as currently this only supports a singular `comment`.
I feel the other fields particularly `authors` and `references` add a lot of value to the users.
If CC Portal doesnt support writing metadata with `authors` and `references` fields, I would expect ICC members to probably not use this feature.

Question;
- Does only supporting `comment` only apply to writing/creating the metadata, OR does it also apply to rendering the metadata in the votes view?

**Comment by KatarinaKeti** [comment]
env: PROD

Test passed.
