### ISSUE TITLE
Cannot copy link for rationale

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#224]
Hello, please fix the below bugs of critical importance.

The buttons to copy the truncated items in the screenshot below do not work.

![Image](https://github.com/user-attachments/assets/99c662b8-69ea-4b63-94a5-ef248a5ae83c)

The ability to copy the truncated items in the below screenshot do not exist (therefore rendering them useless).

![Image](https://github.com/user-attachments/assets/7a4bded1-ce35-4fb3-b047-9e0824b4ee65)

**Comment by Kale98** [comment]
This has been on BETA env. (https://sancho.constitution.gov.tools/).
