### ISSUE TITLE
Display Name

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#225]
I received feedback that this is confusing. It should say "Display Name" in order to clarify that it is the name of the CC member that will be displayed to users. 

![Image](https://github.com/user-attachments/assets/9ac2c5ed-f4f8-4095-9464-b51ba280f5b6)

**Comment by Kale98** [comment]
This has been deployed on BETA env. (https://sancho.constitution.gov.tools/).
