### ISSUE TITLE
Add User Snaps

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#235]
Usersnaps needs to be added to the CC Portal so that users can give feedback on the CC Portal. 

@kickloop will set it up. He will then provide urls for the Help button and the Feedback button.
@MitarRavilic @Kale98 please can you make sure that the urls get added to these buttons?

![Image](https://github.com/user-attachments/assets/c75869e5-afcd-48eb-a4d5-efdd5231e5b1)

**Comment by KatarinaKeti** [comment]
env: PROD

Test passed.
