### ISSUE TITLE
Banner reminder that this is not MainNet

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#236]
Please add a banner that can be dismissed by the user to the top of the page of the public beta to explain that this is not a mainnet product. 

There is already a component that does this, please use that. Don't spend time making your own. 

The copy reads:

> This version of the Constitutional Committee Portal is for testing & previewing new features. NONE of the information contained herein comes from Cardano MainNet

![Image](https://github.com/user-attachments/assets/67cc0052-6462-48ce-92ea-ac4b61201c31)

**Comment by Kale98** [comment]
This has been deployed on BETA env. (https://sancho.constitution.gov.tools/).
