### ISSUE TITLE
[USERSNAP] the profile name for Input Output should be "Input | Output" however the pipe symbol (|) is not accepted as a valid character when submitting this name for a CC member.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#296]
**Taken at**: http://159.89.108.54/en/latest-updates
**Fields**:
- Noticed an issue?: the profile name for Input Output should be &#34;Input | Output&#34; however the pipe symbol (|) is not accepted as a valid character when submitting this name for a CC member.

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open IntersectMBO/intersect-members-area#155 in Usersnap](https://app.usersnap.com/l/feedback/6648dfff-1d81-45aa-b59f-d939f638293c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Kale98** [comment]
Deployed to both SanchoNet and MainNet.
