### ISSUE TITLE
[USERSNAP] Input output's profile picture looks distorted and doesnt fit into the frame.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#297]
**Taken at**: http://159.89.108.54/en/latest-updates
**Fields**:
- Noticed an issue?: Input output&#39;s profile picture looks distorted and doesnt fit into the frame.

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open IntersectMBO/intersect-members-area#154 in Usersnap](https://app.usersnap.com/l/feedback/c370a6f0-bf22-40a4-b3cb-cb6b1a83bd2d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Thomas-Upfield** [comment]
This was the image from IO's media kit
![iohk-symbol](https://github.com/user-attachments/assets/3c84a094-80ab-47d8-aabb-72c5e795ca20)

**Comment by bosko-m** [comment]
This is no longer the case.
