### ISSUE TITLE
[USERSNAP] Table of contents in mobile is in the way of reading the contents of the constitution.  Lots of other smaller issues with mobile.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#298]
**Taken at**: https://sancho.constitution.gov.tools/en
**Fields**:
- Noticed an issue?: Table of contents in mobile is in the way of reading the contents of the constitution.  Lots of other smaller issues with mobile.

**Browser**: Chrome 127 (Android 10)
**Screen size**: 360x640
**[Open IntersectMBO/intersect-members-area#148 in Usersnap](https://app.usersnap.com/l/feedback/4a3cfd96-9b75-4982-bdde-d9efa34aa5b6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
This one is no longer the case.
