### ISSUE TITLE
💡 Bump DBSync versions to 13.5.0.1 and Node to 9.1.1

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/cc-portal#322]
### Is there new design needed?

No

### What?

- Bump all DBSync versions to 13.5.0.1 to align good with the 9.1.1 node hotfix
- Bump all Node versions to 9.1.1 to apply hot fix

### Why?

- To apply hot fix and ensure nodes are healthy
- To make sure that the app stays healthy with the newest version of DBSync after the hot fix has been applied to the node

### How?

Increment versions
DBSync release - https://github.com/IntersectMBO/cardano-db-sync/releases/tag/13.5.0.1
Some extra details on the DBSync migration [here](https://docs.google.com/document/d/1d4j1vXr197hRU94Sqmgq8Ynigyp11JtrR3u8Xm7dV4A/edit#heading=h.uhsua3z3l6ah)

**Comment by bosko-m** [comment]
DBSync is now 13.5.0.1
Node is now 9.1.1

@Kale98 Please advise on the potential code changes you could have due to the above.

**Comment by KatarinaKeti** [comment]
Confirmed by DevOps team.
