### ISSUE TITLE
🐛 ipfs for rationale unreachable

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/cc-portal#327]
### Domain

sancho.constitution.gov.tools

### Context

Setting rationale went fine and the link was generated. While trying to fetch the ipfs content, it never completes and its returning 422 error code and then 504.

### Steps to reproduce

1. Go to the portal
2. Pick one gov action
3. Add rationale to get the ipfs link
4. Try to access the link

### Actual behavior

Content doesnt load

### Expected behavior

Content should load

**Comment by KatarinaKeti** [comment]
Everything is good on BE side as you mentioned, but when it comes to IPFS, it depends on the nodes and the network itself. It can take some time to upload, also it can happen that the files uploaded on IPFS are not available due to network errors and speed, which are not in our control.
