### ISSUE TITLE
Setting the S3 access policy to public

### ISSUE THREAD

**Issue by Kale98** [IntersectMBO/cc-portal#329]
Could you please double check that the S3 access policy has been set up to public, since we are getting the issue like it has not been set up. @aaboyle878 @bosko-m @Ryun1

**Comment by aaboyle878** [comment]
@Kale98 I have spoke with Sava and it should be sorted now, I had enabled server side encryption which has now been disabled

**Comment by Kale98** [comment]
Thank you @aaboyle878. I will close this one.
