### ISSUE TITLE
Standardize the format for GA title

### ISSUE THREAD

**Issue by Kale98** [IntersectMBO/cc-portal#330]
Could you please standardize the format of the GA title? Currently, it appears in two different formats:

- (https://raw.githubusercontent.com/MSzalowski/gov_action_test/main/data%20(1).jsonld
- (https://raw.githubusercontent.com/Ryun1/metadata/main/cip100/ga.jsonld)

This inconsistency is causing the title to be present in some cases and missing in others.

@Ryun1 @bosko-m

**Comment by Kale98** [comment]
@Ryun1 Do you have a chance to look into this? Your advice is much needed.

**Comment by Ryun1** [comment]
> (https://raw.githubusercontent.com/MSzalowski/gov_action_test/main/data%20(1).jsonld

`"@value"` is mistakenly added

**Comment by bosko-m** [comment]
@Kale98 Is this deployed?

**Comment by Kale98** [comment]
@bosko-m yes. We use CIP-108 standard to download GA title and GA abstract.
