### ISSUE TITLE
[CC-PORTAL-FEEDBACK] please put your JavaScript hereasdf

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#349]
**Taken at**: http://209.38.192.168/en/interim-constitution
**Fields**:
- Noticed an issue?: please put your JavaScript hereasdf

![SCREENSHOT](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/a50807c8-1176-46ca-bd0d-dab27eb46118-annotated_76a5b1d4-a56e-46ad-ada2-32ffa00280e9.png?etag=69f74f1d8de02e7d63ff15be1fee3aaf)
*[Download original image](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/a50807c8-1176-46ca-bd0d-dab27eb46118-annotated_76a5b1d4-a56e-46ad-ada2-32ffa00280e9.png?etag=69f74f1d8de02e7d63ff15be1fee3aaf)*

**Browser**: Chrome 126 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1854x935
**[Open #4 in Usersnap](https://app.usersnap.com/l/feedback/e5bee6b9-69a9-4750-a01f-016adb1dd5f8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Insufficient details.
