### ISSUE TITLE
[USERSNAP] There isn't a 'join now' button

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#367]
**Taken at**: https://www.intersectmbo.org/
**Fields**:
- Noticed an issue?: There isn&#39;t a &#39;join now&#39; button

![SCREENSHOT](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/f24f9dcc-a282-43e7-9875-c5d0353c7677-annotated_ccd629c6-c9fc-4ecc-86ed-b6333a0dfd5d.png?etag=9a91c6b1ae70536c7e68932722cbc6d1)
*[Download original image](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/f24f9dcc-a282-43e7-9875-c5d0353c7677-annotated_ccd629c6-c9fc-4ecc-86ed-b6333a0dfd5d.png?etag=9a91c6b1ae70536c7e68932722cbc6d1)*

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1920x1200
**Browser size**: 1536x825
**[Open #6 in Usersnap](https://app.usersnap.com/l/feedback/1ccc459c-7d8c-44ee-854c-61b84fe5e31c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Be part of Intersect button is available further down on the landing page and then Join button on the subsequent page. Closing.

![Image](https://github.com/user-attachments/assets/9ef73da4-8ac2-4c94-9b22-d17d44f2944d)
![Image](https://github.com/user-attachments/assets/2b5ecdd2-cd6f-424d-ace1-155b650cde8e)
