### ISSUE TITLE
[USERSNAP] Error Reporting Idea: Widget Closure and API Key Issue

### ISSUE THREAD

**Issue by KatarinaKeti** [IntersectMBO/cc-portal#388]
Description: When attempting to report an idea, the widget is closed, and an error message appears in the console: “Make sure that the correct apiKey is used and that the project is set live.”

**Expected Behavior**: The widget should allow users to report ideas without errors, even if it has been stopped.

**Actual Behavior**: The widget closes, and an error regarding the API key and project status is displayed in console.

**Comment by bosko-m** [comment]
@kickloop Can you check the widget status in usersnap?

**Comment by KatarinaKeti** [comment]
This is solved. 

env: all

Test passed.
