### ISSUE TITLE
Admin Invitation Management Enhancements

### ISSUE THREAD

**Issue by KatarinaKeti** [IntersectMBO/cc-portal#390]
Possible solutions include:

1. Introducing a "Resend Invitation" feature.
2. Allowing registration with the same email if the current member is inactive.
3. Implementing a "Hard Delete" option.

The Product Requirement document:
https://docs.google.com/document/d/1vbqUl1idWjUGG9By1V4Yws_y5Zwl-D5L4hJj9XvqaTY/edit?usp=sharing

**Comment by Kale98** [comment]
Since this was an idea with 3 separate feature enhancements, I will log them separatly for easier tracking.

**Comment by Kale98** [comment]
Deployed to both SanchoNet and MainNet.
