### ISSUE TITLE
[CC-PORTAL-FEEDBACK] Pipe "|" character in display name causes error.  We need a pipe character to properly express our brand.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#407]
**Taken at**: https://p3000-z3feaf6d9-zc6a664da-gtw.z1add53af.slab.sh/en/governance-actions
**Fields**:
- Noticed an issue?: Pipe &#34;|&#34; character in display name causes error. 

We need a pipe character to properly express our brand.

![SCREENSHOT](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/4c482e15-65f6-4e27-8a94-b9767a9810d5-annotated_cfc129a9-42d9-4113-82b6-e26c791760cb.png?etag=96dce3ccdadbc6a9a03b9827dc4c26ca)
*[Download original image](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/4c482e15-65f6-4e27-8a94-b9767a9810d5-annotated_cfc129a9-42d9-4113-82b6-e26c791760cb.png?etag=96dce3ccdadbc6a9a03b9827dc4c26ca)*

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1368x912
**Browser size**: 1368x785
**[Open #16 in Usersnap](https://app.usersnap.com/l/feedback/e4fcf19a-7328-4a33-837a-1023ace837a5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Dupllicate of #296
