### ISSUE TITLE
Delete Accounts

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/cc-portal#409]
Problem: Cardano Japan and CF are unable to properly register because they are unable to gain access to their accounts. Furthermore there are old accounts that should never have been created cluttering up the admin dashboard.

Solution: delete the following Constitutional Member accounts from the portal:
- thomas.xxxxx@intersectmbo.org
- hixxxxxx@gmail.com
- cardanoatlaxxxxxxx@protonmail.com
- xxxxx@cardanofoundation.org

I have redacted some of the details from these emails but I'm sure you'll be able to work out which ones you need to delete.

**Comment by bosko-m** [comment]
I suppose we should close this one @Kale98 @rogankool ?
