### ISSUE TITLE
Display Rationale URL Without Fetching Content

### ISSUE THREAD

**Issue by rogankool** [IntersectMBO/cc-portal#411]
As a CC Member, I want to ensure that for rationale linked to a vote, only the URL stored in db-sync is retrieved and displayed on the CC portal, without fetching or reading the actual content from the URL, so that the rationale is presented efficiently without relying on external data retrieval processes.

**Acceptance Criteria**
- The URL tied to the rationale in db-sync should be displayed in the CC portal for the corresponding vote.
- No data should be fetched or displayed from the content of the URL.
- Example: If the rationale URL is https://ipfs.io/ipfs/QmZGxmZ73YUzP8YByz5XsxQKKbu9XHnczW8bTJvzyaHVoi, only the URL should be shown, not the content within it.

**Comment by Kale98** [comment]
Deployed to both SanchoNet and MainNet.
