### ISSUE TITLE
Rationale Link Preview - Available/Not Available

### ISSUE THREAD

**Issue by rogankool** [IntersectMBO/cc-portal#416]
As a CC member, I want to be able to quickly see if a rationale has been provided to a vote, so that I have quick overview and access to provided rationales.

Acceptance Criteria
- If a rationale has not been provided, the vote update should state "Not Available" under the "Rationale" subsection preview; also, under the "Show More" modal, it should clearly state that a rationale has not been provided.
- If a rationale has been provided, then the vote update should state "Available" under the "Rationale" subsection preview; and also a link with the ability to quickly copy the link should be displayed under the "Show More" modal.

![Image](https://github.com/user-attachments/assets/d748f376-3638-4b91-8d75-bbfe3c736602)
![Image](https://github.com/user-attachments/assets/4dbeaf59-2017-47ed-81d8-e5ad1d3c39e7)
![Image](https://github.com/user-attachments/assets/d276b537-e927-48ae-b6b9-c3414842c326)

**Comment by Kale98** [comment]
Deployed to both SanchoNet and MainNet.
