### ISSUE TITLE
Latest Updates (UX UI improvements)

### ISSUE THREAD

**Issue by rogankool** [IntersectMBO/cc-portal#420]
As a user, I want to have the latest governance action updates displayed in a clear manner, so that I can have all of the relevant data presented.

As a user, I want to be able to access details with regards to governance action update, so that I can see the governance action abstract and the rationale behind the vote if it was provided.

ACCEPTANCE CRITERIA

This revamp includes making the GA title not clickable, and both the GA description and the rationale is going to be put in the same modal - that is, having only one button stating "Show more"

ADDITIONAL IMPROVEMENTS
Page
- [ ] Improving the alignment of labels and titles
- [ ] Removing the rounded rectangle around the GA title and category
- [ ] Adding the vote time stamp

Modal
- [ ] Removing the scroll
- [ ] Rephrase "GA submitted on: ____"
- [ ] Add a "GA expiration date: _____"

WIREFRAMES:

1) Page - with two versions of an update, mostly differing with text displaying if rationale is available or no
![Image](https://github.com/user-attachments/assets/c8096a16-b6cf-4fd5-b66c-d624715631e4)

2a) "Show More" modal - with rationale available
![Image](https://github.com/user-attachments/assets/9846cb34-3ff0-4a33-8997-8ab40bbd1999)

2a) "Show More" modal - with rationale available
![Image](https://github.com/user-attachments/assets/2e58fd44-57a4-4f56-bde0-b9050168741a)

**Comment by rogankool** [comment]
Improved wireframes @Kale98 @Vojimirovich

**Comment by Kale98** [comment]
This has been deployed to both SanchoNet, and MainNet. 
The future and remaining improvements will be logged and tracked in separate issues.
