### ISSUE TITLE
Navigation Side Bar: visual known issues

### ISSUE THREAD

**Issue by rogankool** [IntersectMBO/cc-portal#425]
Here are some initial issues along with their proposed solutions:
- [x] Content headings should be uniformly truncated based on pixel width rather than character count, ensuring consistent visual alignment.
- [x] Desktop: On hover, display the full heading text; Mobile: adjust truncation width to show more of the title.
- [x] Including the H4 heading should resolve nesting and related issues.
- [ ] A selected heading title should remain highlighted to clearly indicate the chosen content item.

**Comment by Kale98** [comment]
As agreed on today's meeting, we are aiming to release the first 3 changes today to the SanchoNet, and after that, plan the 4th change for the next Release. 

cc @bosko-m @Thomas-Upfield

**Comment by Kale98** [comment]
Current status: 

*Completed:**
* Truncate text by length.
* Ensure full text is visible on hover for truncated text (on mobile, expand only for now until Alex finds a solution).
* Include `<h4>` in the Contents section.
Minor fixes:
- Table of contents links scroll too far, causing the title to be hidden behind the navbar (fix applied to desktop version).
- Resolved hydration-error that was popping up on constitution page.
- Sections in Appendix I and II are not indented like the others.
- Clicking on the Accordion should only expand it without triggering link scrolling.
**To Do:**
* Highlight selected heading in the contents?
* Layout issues on smaller devices (iPhone 12 Pro, Galaxy S8+); likely related to `MDXRemote` component.
*

**Comment by Kale98** [comment]
Deployed to both SanchoNet and MainNet.
