### ISSUE TITLE
Privacy Policy and Terms of Service

### ISSUE THREAD

**Issue by Kale98** [IntersectMBO/cc-portal#429]
@bosko-m @Thomas-Upfield Could you please provide Privacy Policy and Terms of Service so we can link them on CC portal? Currently, those are dead links on the landing page. 

Once the Privacy Policy and Terms of Service are provided by Intersect, link them to the appropriate placeholders in the footer of the landing page. 

As a user, I want to be able to access the Privacy Policy and Terms of Service from the footer of the landing page, so I can review the platform’s legal documents when needed.

### ACCEPTANCE CRITERIA:

- Link Updates: Once the Privacy Policy and Terms of Service are provided by Intersect, link them to the appropriate placeholders in the footer of the landing page. Ensure the links open the correct documents in a new tab for easy access.
- Footer Sections: Privacy Policy link should be labeled "Privacy Policy" in the footer. Terms of Service link should be labeled "Terms of Service" in the footer. 
- Link Verification: Verify that both links are functional and lead to the correct documents. Ensure there are no dead links, and that clicking on either link does not cause any UI issues. 
- Consistency: Ensure that the design and styling of the links match the rest of the footer elements (color, hover state, etc.).

**Comment by bosko-m** [comment]
Im on it. @m-i-k-e Can you help with this?

**Comment by bosko-m** [comment]
@Kale98 Here are the links that you can use:

- Terms of Use - https://docs.intersectmbo.org/legal/policies-and-conditions/terms-of-use
- Privacy Policy - https://docs.intersectmbo.org/legal/policies-and-conditions/privacy-policy

**Comment by Kale98** [comment]
This has been deployed to both SanchoNet and MainNet.
