### ISSUE TITLE
[CC-PORTAL-FEEDBACK] When I am on the homepage and I press the Interim Constitution button in the Nav bar it takes ages to navigate to the page or give me any indication that the page is loading. 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#442]
**Taken at**: https://constitution.gov.tools/en/interim-constitution
**Fields**:
- Noticed an issue?: When I am on the homepage and I press the Interim Constitution button in the Nav bar it takes ages to navigate to the page or give me any indication that the page is loading. 

![SCREENSHOT](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/1996b9bf-b73c-4ff9-91d0-9a41b52a66a5-annotated_ebd8ee94-0b6a-47e9-aeed-ca00514285cb.png?etag=c5917d8bbb59ff415c00dfe7c316cc89)
*[Download original image](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/1996b9bf-b73c-4ff9-91d0-9a41b52a66a5-annotated_ebd8ee94-0b6a-47e9-aeed-ca00514285cb.png?etag=c5917d8bbb59ff415c00dfe7c316cc89)*

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1368x912
**Browser size**: 1368x785
**[Open #20 in Usersnap](https://app.usersnap.com/l/feedback/927ce427-68e9-4838-83d4-529bc1696144?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Will be addressed in #441 .
