### ISSUE TITLE
💡 Improved horizontal navigation

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/cc-portal#447]
### Is there new design needed?

No

### What?

Horizontal navigation on top of the CC Portal app needs to be improved so it enables smooth user journey.

### Why?

Current navigation is rather confusing for the logged in users and differs from non login state.

### How?

* When not logged in it should be as follows:
  * logo top left at the position where it currently is, clicking on it while on any page leads to the main landing page of the app
  * top right part of the horizontal navigation stays as is (Interim Constitution, Members, Latest Updates)
 * When logged in it should be as follows:
   * logo top left at the position where it currently is, clicking on it while on any page leads to the main landing page of the app
   * search field and add new member should go to the second "row" so search becomes wider and aligned on the left and add new member is aligned on the right of that "second" row
   * navigation items are in the following order (Interim Constitution, Members (selected), Latest Updates, My Actions)
   * upload new version button is moved to the top right corner of the interim constitution page only when you have permission to do so and you are logged in of course
   * members page when you are logged in as admin/superadmin or any other role that has permissions to add members whould see a table, any other should se a card members view
   * My actions page tabs should respect in its colors and size the design already used in horizontal top navigation

**Comment by bosko-m** [comment]
@Kale98 Please let Aleksandra do the design so we can all opine before jumping into the implementation.

**Comment by rogankool** [comment]
@bosko-m please check my comments below

CHECKED on MAINNET
* When not logged in it should be as follows:
    * logo top left at the position where it currently is, clicking on it while on any page leads to the main landing page of the app
        * Already is like this on mainnet
    * top right part of the horizontal navigation stays as is (Interim Constitution, Members, Latest Updates)
        * Already is like this on mainnet

CHECKED on DEV
* When logged in it should be as follows:
    * logo top left at the position where it currently is, clicking on it while on any page leads to the main landing page of the app
        * OK, Currently leads to Interim Constitution page
    * search field and add new member should go to the second "row" so search becomes wider and aligned on the left and add new member is aligned on the right of that "second" row
        * OK, see proposed wireframe below
    * navigation items are in the following order (Interim Constitution, Members (selected), Latest Updates, My Actions)
        * Already is like this?
    * upload new version button is moved to the top right corner of the interim constitution page only when you have permission to do so and you are logged in of course
        * OK, noted
    * members page when you are logged in as admin/superadmin or any other role that has permissions to add members whould see a table, any other should se a card members view
        * OK, noted
    * My actions page tabs should respect in its colors and size the design already used in horizontal top navigation
        * OK, noted

![Image](https://github.com/user-attachments/assets/675d3b4d-3bec-4e16-8df3-f9bf9e259813)

**Comment by bosko-m** [comment]
@rogankool When not logged in it should be as follows
_Ok, we have an understanding for this one._

When logged in it should be as follows:
* navigation items are in the following order (Interim Constitution, Members (selected), Latest Updates, My Actions)
  * Already is like this?
_Well technically no, as you can see on the same screenshot you shared. Lets have a quick walkthrough on the daily standup tomorrow._

**Comment by rogankool** [comment]
To streamline navigation and improve consistency, we propose the following adjustments:

Logged-in Admin/Super Admin:
- Unified Members Page: Display a single, tabular Members view (with options to add, delete, or change status of members) in the Members tab. **This change removes redundancy and eliminates the need for the admin dashboard, as the tabular Members view includes all necessary features.**
- Upload New Version Button: Relocate the "Upload New Version" button to the Interim Constitution tab, making it accessible directly from the main navigation rather than within the admin dashboard.

CC Members:
- Ensure the above features are available with appropriate permissions (e.g., permission to upload a new constitution version but no access to member management).

Guest Users:
- Retain the card view for the Members page as it currently is.

Consistent CTA Styling:
- Ensure all call-to-action buttons (e.g., "Add New Member" on the Members page and "Upload New Version" on the Constitution page) follow a consistent design: dark blue background with white text.

@Kale98 @bosko-m do I need to create a wireframe or should we include Aleksandra here?

**Comment by bosko-m** [comment]
@rogankool This is a good outline of what we have discussed. For the wireframe and including Aleksandra, do what you did before. I suppose these changes should end up in Figma.

**Comment by bosko-m** [comment]
@rogankool @Kale98 
When not logged in - **correct**, verified on Sancho.
When logged in:
- logo top left at the position where it currently is, clicking on it while on any page leads to the main landing page of the app - **not correct**. At lease one occurrence not working. When on interim constitution page it doesnt lead you to ladning page but stays on the interim constitution page
- search field and add new member should go to the second "row"  - **correct**
- navigation items are in the following order - **correct**
- upload new version button is moved to the top right corner of the interim constitution page - **correct**
- members page when you are logged in as admin/superadmin or any other role that has permissions - **correct**
- My actions page tabs should respect in its colors and size the design already used in horizontal top navigation - **correct**

Only one issue thats not properly handed, so raise the separate issue and close this one. This is not a showstopper for the release.
