### ISSUE TITLE
Version History: Footer alignment

### ISSUE THREAD

**Issue by rogankool** [IntersectMBO/cc-portal#491]
After the (fix) release on Dec 5th, the footer has been misaligned a bit upwards, it needs to be glued to the bottom, as is the case with all the other pages.

**Comment by bosko-m** [comment]
Seems fine.
@rogankool @Kale98 Raise separate issue for minor UI prob, vertical centering of the footer. Should be done so vertical centers of footer links and button on the left are aligned.
<img width="1418" alt="Image" src="https://github.com/user-attachments/assets/aecc1200-70a2-49b6-aaed-05b89c4100a4" />
